rabbitmq:
  enabled: true
  url: ${CLOUDAMQP_URL}
  thread-pool-size: 8

logging:
  pattern:
    console: "type=%level logger=%class{20} thread=%thread request_id=%X{request_id} client_id=%X{client_id} device_id=%X{device_id} :%m%n"
    file: "type=%level logger=%class{20} thread=%thread request_id=%X{request_id} client_id=%X{client_id} device_id=%X{device_id} :%m%n"

wutsi:
  newsletter:
    asset-url: "https://prod-wutsi.s3.amazonaws.com/static/newsletter-server"
    tracking-url: "https://int-com-wutsi-track.herokuapp.com"
